ALTER TABLE TABMATRICULAS DROP CONSTRAINT 
DROP TABLE TABROTAS;
DROP TABLE TABMARCAS;
DROP TABLE TABMODELOS;
DROP TABLE TABVIATURAS;
DROP TABLE TABMOTORISTAS;
DROP TABLE TAB_CIRCULACAO;

select * from tabrotas;

CREATE TABLE TABROTAS(
ID_ROTA INT NOT NULL IDENTITY PRIMARY KEY,
DESIGNACAO_ROTA NVARCHAR(80) NOT NULL,
TIPO_ROTA NVARCHAR(30) NOT NULL,
CONSTRAINT CHK_TIPOROTA_TABROTAS CHECK(TIPO_ROTA IN('Ida', 'Volta', 'Ida/Volta')),
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE TABMARCAS(
ID_MARCA INT NOT NULL IDENTITY PRIMARY KEY,
DESIGNACAO_MARCA NVARCHAR(80) NOT NULL,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE TABMODELOS(
ID_MODELO INT NOT NULL IDENTITY PRIMARY KEY,
ID_MARCA INT NOT NULL,
DESIGNACAO_MODELO NVARCHAR(80) NOT NULL,
CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_IDMARCA_TABMODELOS FOREIGN KEY(ID_MARCA) REFERENCES TABMARCAS(ID_MARCA));

CREATE TABLE TABVIATURAS(
ID_VIATURA INT NOT NULL IDENTITY PRIMARY KEY,
ID_MODELO INT NOT NULL,
OCUPACAO INT NOT NULL,
TIPO_COMBUSTIVEL NVARCHAR(20) NOT NULL,
QTD_COMBUSTIVEL FLOAT NOT NULL,
MATRICULA NVARCHAR(20) NOT NULL,
CONSTRAINT FK_IDMODELO_VIATURA FOREIGN KEY(ID_MODELO) REFERENCES TABMODELOS(ID_MODELO),
CONSTRAINT CHK_TIPOCOMBUSTIVEL_TABVIATURAS CHECK(TIPO_COMBUSTIVEL IN('Gasolina', 'Gasoleo')));

CREATE TABLE TABMOTORISTAS(
ID_MOTORISTA INT NOT NULL IDENTITY PRIMARY KEY,
NOME NVARCHAR(100) NOT NULL,
MORADA NVARCHAR(100) NULL,
BAIRRO NVARCHAR(100) NULL,
COMUNA [nvarchar](100) NULL,
MUNICIPIO [nvarchar](100) NULL,
ID_PROVINCIA INT NULL DEFAULT ((-1)),
DATANASC DATETIME NOT NULL DEFAULT (getdate()),
GENERO NVARCHAR(1) NOT NULL,
CARTA_CONDUCAO NVARCHAR(60) NOT NULL,
TELEFONE NVARCHAR(20) NULL,
EMAIL NVARCHAR(60) NULL,
CONSTRAINT FK_IDPROVINCIA_TABMOTORISTAS FOREIGN KEY(ID_PROVINCIA) REFERENCES TABPROVINCIAS(IDPROVINCIA),
CONSTRAINT CHK_GENERO_TABMOTORISTAS CHECK(GENERO IN('M', 'F')));

CREATE TABLE TABCIRCULACAO(
ID_CIRCULACAO INT NOT NULL IDENTITY PRIMARY KEY,
ID_MOTORISTA INT NOT NULL,
ID_VIATURA INT NOT NULL,
ID_ROTA INT NOT NULL,
INICIO TIME NOT NULL,
TERMINO TIME NOT NULL,
CONSTRAINT FK_IDMOTORISTA_TABCIRCULACAO FOREIGN KEY(ID_MOTORISTA) REFERENCES TABMOTORISTAS(ID_MOTORISTA),
CONSTRAINT FK_IDVIATURA_TABCIRCULACAO FOREIGN KEY(ID_VIATURA) REFERENCES TABVIATURAS(ID_VIATURA),
CONSTRAINT FK_IDROTA_TABCIRCULACAO FOREIGN KEY(ID_ROTA) REFERENCES TABROTAS(ID_ROTA));

ALTER TABLE TABMATRICULAS ADD ID_CIRCULACAO INT DEFAULT NULL;

ALTER TABLE TABMATRICULAS ADD CONSTRAINT FK_IDCIRCULACAO_TABMATRICULAS FOREIGN KEY(ID_CIRCULACAO) REFERENCES TABCIRCULACAO(ID_CIRCULACAO);


